import io.netty.resolver.dns.DnsNameResolverException;
public class FunctionUse23414 {
public void funcUse() {
DnsNameResolverException dnsnameresolverexception = new DnsNameResolverException();
dnsnameresolverexception.fillInStackTrace();
}
}